// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
  // KV Namespace containing articles
  ARTICLES: KVNamespace;
}
